# ansible-playbook -i <hostname>, generate-ign.yml

---
- hosts: all
  connection: local
  gather_facts: no

  pre_tasks:
    - name: create host path in manifests/
      file:
        path: "manifests/{{ inventory_hostname }}"
        state: directory

  tasks:
    - name: template .bu files in manifests/
      template:
        src: fcos-no-gpg-kube-install-bu.j2
        dest: "manifests/{{ inventory_hostname }}/fcos.bu"
      diff: true

    - name: butane - generate ingnition file
      shell: |
        butane --pretty --strict --files-dir /opt/fcos-ops/scripts < manifests/{{ inventory_hostname }}/fcos.bu > manifests/{{ inventory_hostname }}/fcos.ign
      changed_when: no

    - name: generate environment file
      copy:
        dest: "manifests/{{ inventory_hostname }}/fcos.env"
        content: |
          export IGN_CONFIG=/opt/fcos-ops/manifests/{{ inventory_hostname }}/fcos.ign
          export IMAGE=/opt/fcos/images/fedora-coreos-36.20221014.3.1-qemu.x86_64.qcow2
          export VM_NAME={{ inventory_hostname }}
          export VCPUS=2
          export RAM_MB=4096
          export DISK_GB=10
          export STREAM=stable
