all:
  vars:
  children:

    default_cluster:
      hosts:
        node1.default:
        node2.default:
        node3.default:

    demo_cluster:
      hosts:
        node1.demo:
        node2.demo:

    white_widow:
      vars:
        cluster_name: white-widow
      hosts:
        node1.white-widow:
          variable_1: data
          variable_2: data
        node2.white-widow:

    golden_goat:
      vars:
        cluster_name: golden-goat
      hosts:
        node1.golden-goat:
        node2.golden-goat:


    # Ungrouped hosts
    ungrouped: {}
